apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-service
  namespace: sadp
  labels:
    app: development-service
    component: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: development-service
  template:
    metadata:
      labels:
        app: development-service
        component: backend
        version: v1
    spec:
      serviceAccountName: development
      containers:
      - name: development-service
        image: us-central1-docker.pkg.dev/sarthi-patient-experience-hub/sarthi-services/development-service:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: GCP_PROJECT_ID
          value: "sarthi-patient-experience-hub"
        - name: GCP_REGION
          value: "us-central1"
        - name: ENVIRONMENT
          value: "production"
        - name: PUBSUB_TOPIC
          value: "development-topic"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: connection-string
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret-key
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      nodeSelector:
        workload: general
---
apiVersion: v1
kind: Service
metadata:
  name: development-service
  namespace: sadp
  labels:
    app: development-service
spec:
  type: ClusterIP
  selector:
    app: development-service
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: development-service-hpa
  namespace: sadp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: development-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80