apiVersion: v1
kind: Namespace
metadata:
  name: sadp
  labels:
    name: sadp
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sadp-quota
  namespace: sadp
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sadp-limits
  namespace: sadp
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container