steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build' 
      - '-t' 
      - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:latest'
      - '.'
    dir: 'SADP/services/kaggle-integration'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push' 
      - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push' 
      - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sadp-kaggle-integration'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/sadp-kaggle-integration:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s